// frontend/src/components/StatusBanner.jsx
import React from 'react';
import { ShieldCheck, AlertTriangle, AlertOctagon, HelpCircle } from 'lucide-react';

export default function StatusBanner({ riskResult }) {
  if (!riskResult) {
    return (
      <div className="bg-card border border-border rounded-xl p-5 shadow-lg flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-slate-800 flex items-center justify-center text-slate-400">
            <HelpCircle className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-300">Awaiting Vehicle Observation</h3>
            <p className="text-xs text-slate-400">Stream camera feed or run a test scenario clip to initiate verification</p>
          </div>
        </div>
        <span className="px-3 py-1 rounded-full text-xs font-mono bg-slate-800 text-slate-400 border border-slate-700">
          STANDBY
        </span>
      </div>
    );
  }

  const { risk_level, risk_score, reason, plate_number } = riskResult;

  const isGreen = risk_level === "GREEN";
  const isYellow = risk_level === "YELLOW";
  const isRed = risk_level === "RED";

  let bgClass = "bg-emerald-950/30 border-emerald-500/40 text-emerald-400";
  let badgeClass = "bg-emerald-500/20 text-emerald-300 border-emerald-500/50";
  let title = "LIKELY VALID — IDENTITY CONFIRMED";
  let Icon = ShieldCheck;

  if (isYellow) {
    bgClass = "bg-amber-950/30 border-amber-500/40 text-amber-400";
    badgeClass = "bg-amber-500/20 text-amber-300 border-amber-500/50";
    title = "NEEDS REVIEW — SUSPICIOUS / UNCERTAIN";
    Icon = AlertTriangle;
  } else if (isRed) {
    bgClass = "bg-rose-950/30 border-rose-500/40 text-rose-400";
    badgeClass = "bg-rose-500/20 text-rose-300 border-rose-500/50 animate-pulse";
    title = "HIGH-RISK IDENTITY MISMATCH DETECTED";
    Icon = AlertOctagon;
  }

  return (
    <div className={`border rounded-xl p-5 shadow-xl transition-all duration-300 ${bgClass}`}>
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-start gap-4">
          <div className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${badgeClass}`}>
            <Icon className="w-7 h-7" />
          </div>
          <div>
            <div className="flex items-center gap-3 flex-wrap">
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold font-mono uppercase tracking-wider border ${badgeClass}`}>
                {risk_level} ALERT
              </span>
              <span className="text-xs font-mono text-slate-300">
                Plate: <strong className="text-white text-sm bg-black/40 px-2 py-0.5 rounded border border-white/10">{plate_number}</strong>
              </span>
            </div>
            <h2 className="text-lg font-extrabold tracking-tight mt-1 text-white">
              {title}
            </h2>
            <p className="text-xs text-slate-300 mt-1 max-w-2xl leading-relaxed">
              {reason}
            </p>
          </div>
        </div>

        <div className="flex sm:flex-col items-center sm:items-end justify-between border-t sm:border-t-0 border-white/10 pt-3 sm:pt-0">
          <span className="text-xs uppercase tracking-wider text-slate-400 font-mono">Risk Anomaly Score</span>
          <div className="flex items-baseline gap-1 mt-0.5">
            <span className="text-3xl font-black font-mono tracking-tight text-white">
              {risk_score}%
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/StatusBanner.vue
<script setup>
import { computed } from 'vue'
import {
  ShieldAlert,
  AlertTriangle,
  CheckCircle,
  X
} from 'lucide-vue-next'

const props = defineProps({
  riskResult: {
    type: Object,
    default: null
  },
  visible: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['dismiss'])

const isHighRisk = computed(() => {
  const score = props.riskResult?.risk_score || 0
  return score >= 60 || props.riskResult?.risk_level === 'RED'
})

const isWarning = computed(() => {
  const score = props.riskResult?.risk_score || 0
  return score >= 30 && score < 60
})
</script>

<template>
  <transition
    enter-active-class="transform ease-out duration-300 transition"
    enter-from-class="translate-y-2 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition ease-in duration-150"
    leave-from-class="opacity-100"
    leave-to-class="opacity-0"
  >
    <div
      v-if="visible && (isHighRisk || isWarning)"
      class="rounded-xl border shadow-card p-4 transition-all"
      :class="isHighRisk
        ? 'bg-rose-50/95 border-rose-300 text-rose-900'
        : 'bg-amber-50/95 border-amber-300 text-amber-900'"
    >
      <div class="flex items-start justify-between">
        <div class="flex items-start space-x-3">
          <div
            class="p-2 rounded-lg flex-shrink-0 mt-0.5"
            :class="isHighRisk ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'"
          >
            <ShieldAlert v-if="isHighRisk" class="w-5 h-5 animate-pulse" />
            <AlertTriangle v-else class="w-5 h-5" />
          </div>
          <div>
            <div class="flex items-center space-x-2">
              <span class="text-xs font-bold uppercase tracking-wider">
                {{ isHighRisk ? 'CRITICAL IDENTITY TAMPERING ALERT' : 'ATTRIBUTE VARIANCE DETECTED' }}
              </span>
              <span class="font-mono text-xs font-extrabold px-2 py-0.5 rounded bg-white/80 border border-zinc-300">
                {{ (riskResult?.plate_number || 'UNKNOWN').toUpperCase() }}
              </span>
            </div>
            <p class="text-xs mt-1 font-medium leading-relaxed">
              {{ riskResult?.reasons?.[0] || 'Vehicle attributes do not match official VAHAN registry records.' }}
            </p>
          </div>
        </div>

        <button
          @click="emit('dismiss')"
          type="button"
          class="p-1 rounded-lg text-zinc-400 hover:text-zinc-600 transition-colors"
        >
          <X class="w-4 h-4" />
        </button>
      </div>
    </div>
  </transition>
</template>
